export const USER_SIGNED_UP_SUCCESS = 'USER_SIGNED_UP_SUCCESS';
export const USER_SIGNED_UP_ERROR = 'USER_SIGNED_UP_ERROR';

export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_IN_ERROR = 'USER_LOGGED_IN_ERROR';

export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
export const USER_LOG_OUT_ERROR = 'USER_LOG_OUT_ERROR';
